"""Afegixo taula de configuració

Revision ID: 6a1d8848928d
Revises: bb1790855be8
Create Date: 2025-06-20 01:43:47.560204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1d8848928d'
down_revision = 'bb1790855be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
