"""Afegixo camp confirmacio necesaria a usuari

Revision ID: bb1790855be8
Revises: c8eab0d91920
Create Date: 2025-06-19 19:34:18.822063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1790855be8'
down_revision = 'c8eab0d91920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuaris', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_needed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuaris', schema=None) as batch_op:
        batch_op.drop_column('confirmation_needed')

    # ### end Alembic commands ###
