"""añado campo observacions en viatges

Revision ID: c8eab0d91920
Revises: 
Create Date: 2025-06-01 01:20:48.732124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8eab0d91920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viatges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacions', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viatges', schema=None) as batch_op:
        batch_op.drop_column('observacions')

    # ### end Alembic commands ###
